version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - HCAPTCHA_SECRET=${HCAPTCHA_SECRET}
      - HCAPTCHA_SITEKEY=${HCAPTCHA_SITEKEY}
    entrypoint: [ 
      "java", 
      "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", 
      "-jar", 
      "/app/app.jar" 
    ]
    networks:
      - devnet

networks:
  devnet:
