# docker-compose.yml  –  Compose V2 no longer needs the top-level “version” key
services:
  backend:
    build:
      context: .
    # Expose application and debug ports
    ports:
      - "8080:8080"
      - "5005:5005"
    # Mount source code and Maven cache for hot-reloading and faster builds
    volumes:
      - ./src:/app/src
      - ~/.m2:/root/.m2
    environment:
        - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
        - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
        - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
        - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
    # Uses default dev profile from application.properties
    entrypoint: [ "java", "-jar", "/app/app.jar",
                  "-Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,
                  server=y,suspend=n,address=*:5005'" ]

    # Load environment variables from the .env file
    env_file:
      - .env