name: Maven Build and Test

on:
  pull_request:
    branches: [ "development" ]
  push:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Cache dependency-check data
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository/org/owasp/dependency-check-data
            ~/.cache/dependency-check
          key: ${{ runner.os }}-dependency-check-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-dependency-check-

      - name: Build and run tests with Maven
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: mvn -B clean verify
